### ISSUE TITLE
can you give a exactly parameters of this tool?

### ISSUE THREAD

**Issue by yunfan** [srch07/HDFSChecksumForLocalfile#1]
hi i found your tool at stackoverflow(https://stackoverflow.com/questions/31920033/checksum-verification-in-hadoop), but when i want to try it , i dont know how to extract give the parameters for it , will you please give a example showing such stuff?

**Comment by srch07** [comment]
This should help you.

It can be fired using java -jar "jar_name" "arguments"

Arguments can be provided in either of the below format:

   1.

   file name with path

   eg, java -jar "this_jar_filename_with_path" "local file path"
   2.

   filename_with_path BytesPerChecksum ChecksumPerBlock

   eg, java -jar "this_jar_filename_with_path" "local file path" 256 512
   3.

   filename_with_path BytesPerChecksum ChecksumPerBlock
   AlgorithmType(CRC32/CRC32C/NULL/DEFAULT/MIXED)

   eg, java -jar "this_jar_filename_with_path" "local file path" 256 512 CRC32C


Regards,
Abhi

**Comment by srch07** [comment]
It can be fired using java -jar "jar_name" "arguments"

Arguments can be provided in either of the below format:

file name with path

eg, java -jar "this_jar_filename_with_path"

filename_with_path BytesPerChecksum ChecksumPerBlock

eg, java -jar "this_jar_filename_with_path" 256 512

filename_with_path BytesPerChecksum ChecksumPerBlock AlgorithmType(CRC32/CRC32C/NULL/DEFAULT/MIXED)

eg, java -jar "this_jar_filename_with_path" 256 512 CRC32C

**Comment by yunfan** [comment]
thanks, i'd tried the parameters you gave, the result is still not equal to the result from hdfs dfs -checksum
i knew that must caused by the wrong parameters i'd gave, but how can i get the same BytesPerChecksum and ChecksumPerBlock from `hadoop dfs` tool?
